// Package products provides access to the Ecwid products API.
package products

import "encoding/json"

// Product represents a product in Ecwid.
type Product struct {
	ID             int64            `json:"id"`
	SKU            string           `json:"sku,omitempty"`
	Quantity       *int             `json:"quantity,omitempty"`
	Unlimited      *bool            `json:"unlimited,omitempty"`
	InStock        *bool            `json:"inStock,omitempty"`
	Name           string           `json:"name,omitempty"`
	NameTranslated *json.RawMessage `json:"nameTranslated,omitempty"`

	Price                 float64         `json:"price,omitempty"`
	PriceInProductList    float64         `json:"priceInProductList,omitempty"`
	WholesalePrices       json.RawMessage `json:"wholesalePrices,omitempty"`
	CompareToPrice        float64         `json:"compareToPrice,omitempty"`
	LowestPrice           float64         `json:"lowestPrice,omitempty"`
	LowestPriceSettings   json.RawMessage `json:"lowestPriceSettings,omitempty"`
	IsShippingRequired    *bool           `json:"isShippingRequired,omitempty"`
	Weight                float64         `json:"weight,omitempty"`
	URL                   string          `json:"url,omitempty"`
	AutogeneratedSlug     string          `json:"autogeneratedSlug,omitempty"`
	CustomSlug            string          `json:"customSlug,omitempty"`
	Created               string          `json:"created,omitempty"`
	Updated               string          `json:"updated,omitempty"`
	CreateTimestamp       int64           `json:"createTimestamp,omitempty"`
	UpdateTimestamp       int64           `json:"updateTimestamp,omitempty"`
	ProductClassID        int64           `json:"productClassId,omitempty"`
	Enabled               *bool           `json:"enabled,omitempty"`
	WarningLimit          int             `json:"warningLimit,omitempty"`
	FixedShippingRateOnly *bool           `json:"fixedShippingRateOnly,omitempty"`
	FixedShippingRate     float64         `json:"fixedShippingRate,omitempty"`

	Description           string           `json:"description,omitempty"`
	DescriptionTranslated *json.RawMessage `json:"descriptionTranslated,omitempty"`
	Subtitle              string           `json:"subtitle,omitempty"`
	SubtitleTranslated    *json.RawMessage `json:"subtitleTranslated,omitempty"`
	Ribbon                json.RawMessage  `json:"ribbon,omitempty"`

	// Media
	ImageURL                               string          `json:"imageUrl,omitempty"`
	SmallThumbnailURL                      string          `json:"smallThumbnailUrl,omitempty"`
	HdThumbnailURL                         string          `json:"hdThumbnailUrl,omitempty"`
	OriginalImageURL                       string          `json:"originalImageUrl,omitempty"`
	OriginalImage                          json.RawMessage `json:"originalImage,omitempty"`
	ThumbnailURL                           string          `json:"thumbnailUrl,omitempty"`
	DefaultDisplayedPrice                  float64         `json:"defaultDisplayedPrice,omitempty"`
	DefaultDisplayedPriceFormatted         string          `json:"defaultDisplayedPriceFormatted,omitempty"`
	CompareToPriceFormatted                string          `json:"compareToPriceFormatted,omitempty"`
	CompareToPriceDiscount                 float64         `json:"compareToPriceDiscount,omitempty"`
	CompareToPriceDiscountFormatted        string          `json:"compareToPriceDiscountFormatted,omitempty"`
	CompareToPriceDiscountPercent          float64         `json:"compareToPriceDiscountPercent,omitempty"`
	CompareToPriceDiscountPercentFormatted string          `json:"compareToPriceDiscountPercentFormatted,omitempty"`
	GalleryImages                          json.RawMessage `json:"galleryImages,omitempty"`
	Media                                  json.RawMessage `json:"media,omitempty"`

	// Classification
	CategoryIDs       []int64         `json:"categoryIds,omitempty"`
	Categories        json.RawMessage `json:"categories,omitempty"`
	DefaultCategoryID int64           `json:"defaultCategoryId,omitempty"`
	ShowOnFrontpage   int             `json:"showOnFrontpage,omitempty"`

	// SEO
	SeoTitle                 string           `json:"seoTitle,omitempty"`
	SeoTitleTranslated       *json.RawMessage `json:"seoTitleTranslated,omitempty"`
	SeoDescription           string           `json:"seoDescription,omitempty"`
	SeoDescriptionTranslated *json.RawMessage `json:"seoDescriptionTranslated,omitempty"`

	// Options & Variations
	Options      json.RawMessage `json:"options,omitempty"`
	Combinations json.RawMessage `json:"combinations,omitempty"`

	// Dimensions
	Dimensions json.RawMessage `json:"dimensions,omitempty"`
	Volume     float64         `json:"volume,omitempty"`

	// Attributes
	Attributes json.RawMessage `json:"attributes,omitempty"`

	// Files
	Files json.RawMessage `json:"files,omitempty"`

	// Tax
	Tax json.RawMessage `json:"tax,omitempty"`

	// Favorites
	IsFavorited *bool `json:"isFavorited,omitempty"`

	// Shipping
	ShippingSettings json.RawMessage `json:"shippingSettings,omitempty"`

	// Subscription
	RecurringChargeSettings json.RawMessage `json:"recurringChargeSettings,omitempty"`
	SubscriptionSettings    json.RawMessage `json:"subscriptionSettings,omitempty"`

	// Other
	RelatedProducts     json.RawMessage `json:"relatedProducts,omitempty"`
	IsSampleProduct     *bool           `json:"isSampleProduct,omitempty"`
	GoogleItemCondition string          `json:"googleItemCondition,omitempty"`
	ExternalReferenceID string          `json:"externalReferenceId,omitempty"`
	CustomsHsTariffCode string          `json:"customsHsTariffCode,omitempty"`
	Brand               string          `json:"brand,omitempty"`
	UPC                 string          `json:"upc,omitempty"`

	// Deprecated but still in API
	OrderBy int `json:"orderBy,omitempty"`
}

// SearchResult is the paginated response from the products search API.
type SearchResult struct {
	Total  int       `json:"total"`
	Count  int       `json:"count"`
	Offset int       `json:"offset"`
	Limit  int       `json:"limit"`
	Items  []Product `json:"items"`
}

// SearchOptions holds query parameters for searching products.
type SearchOptions struct {
	Keyword           string
	PriceFrom         *float64
	PriceTo           *float64
	Category          int64
	WithSubcategories *bool
	SortBy            string
	Offset            int
	Limit             int
	CreatedFrom       string
	CreatedTo         string
	UpdatedFrom       string
	UpdatedTo         string
	Enabled           *bool
	InStock           *bool
	Sku               string
	ProductID         string
	BaseURL           string
	CleanURLs         *bool
	Lang              string
	ResponseFields    string
}

// CreateResult represents the response from creating a product.
type CreateResult struct {
	ID int64 `json:"id"`
}

// UpdateResult represents the response from an update operation.
type UpdateResult struct {
	UpdateCount int `json:"updateCount"`
}

// DeleteResult represents the response from a delete operation.
type DeleteResult struct {
	DeleteCount int `json:"deleteCount"`
}

// Combination represents a product variation (combination) in Ecwid.
type Combination struct {
	ID                  int64           `json:"id"`
	CombinationNumber   int             `json:"combinationNumber,omitempty"`
	Options             json.RawMessage `json:"options,omitempty"`
	SKU                 string          `json:"sku,omitempty"`
	Quantity            *int            `json:"quantity,omitempty"`
	Unlimited           *bool           `json:"unlimited,omitempty"`
	Price               *float64        `json:"price,omitempty"`
	CompareToPrice      *float64        `json:"compareToPrice,omitempty"`
	Weight              *float64        `json:"weight,omitempty"`
	Dimensions          json.RawMessage `json:"dimensions,omitempty"`
	Volume              *float64        `json:"volume,omitempty"`
	SmallThumbnailURL   string          `json:"smallThumbnailUrl,omitempty"`
	HdThumbnailURL      string          `json:"hdThumbnailUrl,omitempty"`
	ThumbnailURL        string          `json:"thumbnailUrl,omitempty"`
	ImageURL            string          `json:"imageUrl,omitempty"`
	OriginalImageURL    string          `json:"originalImageUrl,omitempty"`
	IsDefault           *bool           `json:"isDefault,omitempty"`
	WholesalePrices     json.RawMessage `json:"wholesalePrices,omitempty"`
	WarningLimit        int             `json:"warningLimit,omitempty"`
	Attributes          json.RawMessage `json:"attributes,omitempty"`
	ExternalReferenceID string          `json:"externalReferenceId,omitempty"`
	UPC                 string          `json:"upc,omitempty"`
}

// CombinationSearchResult is the response from listing product combinations.
type CombinationSearchResult struct {
	Total        int           `json:"total,omitempty"`
	Count        int           `json:"count,omitempty"`
	Offset       int           `json:"offset,omitempty"`
	Limit        int           `json:"limit,omitempty"`
	Combinations []Combination `json:"items,omitempty"`
}

// CombinationCreateResult represents the response from creating a combination.
type CombinationCreateResult struct {
	ID int64 `json:"id"`
}

// InventoryUpdate holds fields for updating product or variation inventory.
type InventoryUpdate struct {
	Quantity     *int  `json:"quantity,omitempty"`
	Unlimited    *bool `json:"unlimited,omitempty"`
	WarningLimit *int  `json:"warningLimit,omitempty"`
	InStock      *bool `json:"inStock,omitempty"`
}

// DeletedProductsResult is the paginated response for deleted products history.
type DeletedProductsResult struct {
	Total  int              `json:"total"`
	Count  int              `json:"count"`
	Offset int              `json:"offset"`
	Limit  int              `json:"limit"`
	Items  []DeletedProduct `json:"items"`
}

// DeletedProduct represents a deleted product reference.
type DeletedProduct struct {
	ID   int64  `json:"id"`
	Date string `json:"date"`
}

// DeletedProductsOptions holds query parameters for the deleted products endpoint.
type DeletedProductsOptions struct {
	FromDate string
	ToDate   string
	Offset   int
	Limit    int
}

// SortOrder represents the product sort order for a category.
type SortOrder struct {
	SortedIDs []int64 `json:"sortedIds"`
}

// SortOrderUpdate holds fields for updating the product sort order.
type SortOrderUpdate struct {
	SortedIDs      []int64 `json:"sortedIds"`
	ParentCategory int64   `json:"parentCategory,omitempty"`
}

// FiltersResult represents the response from the product filters endpoint.
type FiltersResult struct {
	Filters json.RawMessage `json:"filters,omitempty"`
}

// ProductClass represents a product type/class.
type ProductClass struct {
	ID             int64           `json:"id"`
	Name           string          `json:"name,omitempty"`
	Attributes     json.RawMessage `json:"attributes,omitempty"`
	GoogleTaxonomy string          `json:"googleTaxonomy,omitempty"`
}

// ProductClassCreateResult represents the response from creating a product class.
type ProductClassCreateResult struct {
	ID int64 `json:"id"`
}

// Brand represents a product brand.
type Brand struct {
	Name         string `json:"name"`
	ProductCount int    `json:"productCount,omitempty"`
}

// BrandsResult represents the response from listing brands.
type BrandsResult struct {
	Brands []Brand `json:"brands,omitempty"`
}

// Swatch represents a product swatch/color option.
type Swatch struct {
	Name   string          `json:"name,omitempty"`
	Colors json.RawMessage `json:"colors,omitempty"`
}

// SwatchesResult represents the response from listing swatches.
type SwatchesResult struct {
	Swatches []Swatch `json:"swatches,omitempty"`
}

// MediaUpdate holds fields for updating product media.
type MediaUpdate struct {
	Images json.RawMessage `json:"images,omitempty"`
	Videos json.RawMessage `json:"videos,omitempty"`
}

// ProductFile represents a downloadable file attached to a product.
type ProductFile struct {
	ID          int64  `json:"id"`
	Name        string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	Size        int64  `json:"size,omitempty"`
	AdminURL    string `json:"adminUrl,omitempty"`
}

// ProductFileUpdate holds fields for updating a product file.
type ProductFileUpdate struct {
	Name        string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
}

// GalleryVideo represents a gallery video for a product.
type GalleryVideo struct {
	ID           int64  `json:"id"`
	URL          string `json:"url,omitempty"`
	ThumbnailURL string `json:"thumbnailUrl,omitempty"`
	Title        string `json:"title,omitempty"`
	Width        int    `json:"width,omitempty"`
	Height       int    `json:"height,omitempty"`
}

// GalleryVideoUpdate holds fields for updating a gallery video.
type GalleryVideoUpdate struct {
	Title string `json:"title,omitempty"`
}
