version: '3'

tasks:
  lint:
    desc: Run golangci-lint on mock module
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - golangci-lint run ./...

  lint:fix:
    desc: Run golangci-lint with auto-fix on mock module
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - golangci-lint run --fix ./...

  test:
    desc: Run tests for mock module
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - go test ./... -race -count=1

  tidy:
    desc: Run go mod tidy for mock module
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - go mod tidy
