// Package categories provides access to the Ecwid categories API.
package categories

import "encoding/json"

// Category represents a product category in Ecwid.
// Docs: https://docs.ecwid.com/api-reference/rest-api/categories/search-categories.md
type Category struct {
	ID                    int64            `json:"id"`
	ParentID              int64            `json:"parentId,omitempty"`
	OrderBy               int              `json:"orderBy,omitempty"`
	HdThumbnailURL        string           `json:"hdThumbnailUrl,omitempty"`
	ThumbnailURL          string           `json:"thumbnailUrl,omitempty"`
	ImageURL              string           `json:"imageUrl,omitempty"`
	OriginalImageURL      string           `json:"originalImageUrl,omitempty"`
	OriginalImage         *json.RawMessage `json:"originalImage,omitempty"`
	Thumbnail             *json.RawMessage `json:"thumbnail,omitempty"`
	Name                  string           `json:"name,omitempty"`
	NameTranslated        *json.RawMessage `json:"nameTranslated,omitempty"`
	URL                   string           `json:"url,omitempty"`
	AutogeneratedSlug     string           `json:"autogeneratedSlug,omitempty"`
	CustomSlug            string           `json:"customSlug,omitempty"`
	ProductCount          int              `json:"productCount,omitempty"`
	EnabledProductCount   int              `json:"enabledProductCount,omitempty"`
	Description           string           `json:"description,omitempty"`
	DescriptionTranslated *json.RawMessage `json:"descriptionTranslated,omitempty"`
	Enabled               *bool            `json:"enabled,omitempty"`
	ProductIDs            []int64          `json:"productIds,omitempty"`
	IsSampleCategory      bool             `json:"isSampleCategory,omitempty"`
}

// SearchResult is the paginated response from the categories search API.
type SearchResult struct {
	Total  int        `json:"total"`
	Count  int        `json:"count"`
	Offset int        `json:"offset"`
	Limit  int        `json:"limit"`
	Items  []Category `json:"items"`
}

// SearchOptions holds query parameters for searching categories.
type SearchOptions struct {
	Keyword           string
	Parent            int64
	ParentIDs         string
	WithSubcategories *bool
	HiddenCategories  *bool
	Offset            int
	Limit             int
	Lang              string
}

// ProductOrderResult is the response from the product order endpoint.
type ProductOrderResult struct {
	SortedIDs []int64 `json:"sortedIds"`
}

// CreateResult represents the response from a create operation.
type CreateResult struct {
	ID int64 `json:"id"`
}

// UpdateResult represents the response from an update operation.
type UpdateResult struct {
	UpdateCount int `json:"updateCount"`
}

// DeleteResult represents the response from a delete operation.
type DeleteResult struct {
	DeleteCount int `json:"deleteCount"`
}
